from __future__ import annotations

from langchain_core.messages import AIMessage

from healthbot.core.logging import get_logger
from healthbot.observability.metrics import metrics

logger = get_logger(__name__)


class SafetyService:
    """Post-process assistant answers with lightweight medical safety guidance."""

    EDUCATIONAL_DISCLAIMER = (
        "This is general educational information and is not a diagnosis. "
        "For personal medical advice, please consult a qualified healthcare professional."
    )

    URGENT_GUIDANCE = (
        "If symptoms are severe, sudden, worsening, or feel like an emergency, "
        "please seek urgent medical care or call emergency services."
    )

    RED_FLAG_PATTERNS = [
        "chest pain",
        "trouble breathing",
        "difficulty breathing",
        "shortness of breath",
        "sudden numbness",
        "numbness on one side",
        "face drooping",
        "slurred speech",
        "vomiting blood",
        "severe abdominal pain",
        "loss of consciousness",
        "fainting",
        "seizure",
        "severe allergic reaction",
        "anaphylaxis",
        "suicidal",
        "harm myself",
        "kill myself",
    ]

    DISCLAIMER_HINTS = [
        "not a diagnosis",
        "not medical advice",
        "general educational information",
        "consult a qualified healthcare professional",
        "consult a healthcare professional",
        "talk to a healthcare professional",
        "speak with a healthcare professional",
        "medical professional",
        "doctor",
    ]

    URGENT_HINTS = [
        "seek urgent medical care",
        "seek immediate medical attention",
        "seek emergency care",
        "call emergency services",
        "call your local emergency number",
        "go to the emergency room",
        "go to the nearest hospital",
        "medical emergency",
    ]

    def apply(self, message: AIMessage, *, question: str = "") -> AIMessage:
        """Apply safety guidance to an AIMessage.

        Parameters
        ----------
        message:
            Assistant message generated by the LLM.
        question:
            Original user question. Used to detect red-flag contexts.

        Returns
        -------
        AIMessage
            A possibly augmented assistant message.
        """
        content = message.content if isinstance(message.content, str) else str(message.content)
        updated_content = content.strip()

        if not updated_content:
            logger.warning("SafetyService received empty answer")
            metrics.increment("safety.empty_answer")
            return AIMessage(
                content=self.EDUCATIONAL_DISCLAIMER,
                additional_kwargs=message.additional_kwargs,
                response_metadata=message.response_metadata,
            )

        if self._is_red_flag_question(question):
            updated_content = self._ensure_urgent_guidance(updated_content)

        updated_content = self._ensure_disclaimer(updated_content)

        if updated_content != content:
            metrics.increment("safety.answer_augmented")

        return AIMessage(
            content=updated_content,
            additional_kwargs=message.additional_kwargs,
            response_metadata=message.response_metadata,
        )

    def _is_red_flag_question(self, question: str) -> bool:
        normalized = question.lower()
        return any(pattern in normalized for pattern in self.RED_FLAG_PATTERNS)

    def _ensure_disclaimer(self, content: str) -> str:
        normalized = content.lower()

        if any(hint in normalized for hint in self.DISCLAIMER_HINTS):
            return content

        return f"{content}\n\n{self.EDUCATIONAL_DISCLAIMER}"

    def _ensure_urgent_guidance(self, content: str) -> str:
        normalized = content.lower()

        if any(hint in normalized for hint in self.URGENT_HINTS):
            return content

        return f"{content}\n\n{self.URGENT_GUIDANCE}"