apiVersion: v1
kind: Service
metadata:
  name: medlearn-agent
  namespace: medlearn
spec:
  type: ClusterIP
  selector:
    app: medlearn-agent
  ports:
    - name: http
      port: 80
      targetPort: 8000